// gsap.timeline({ defaults: { opacity: 1, duration: 1, ease: "power1.in" } })
//   .to("#landing1, #landing2, #landing3, #landing4", {})
//   .to("#landing5", {})
//   .to("#landing6", {})
//   .to("#landing7", {})
//   .to("#landing8", {})
//   .to("#landingOverlay", {})
//   .to("#landingText", {})
// ;

gsap.timeline({ defaults: { opacity: 1, duration: .75, ease: "power1.in" } })
  .to("#landing1", {})
  .to("#landing2", {})
  .to("#landing3", {})
  .to("#landing4", {})
  .to("#landing5", {})
  .to("#landing6", {})
  .to("#landing7", {})
  .to("#landing8", {})
  .to("#landingOverlay", {})
  .to("#landingText", {})
;
